### ISSUE TITLE
show speed and upload percentage

### ISSUE THREAD

**Issue by ihubgit** [SkyLabs-Innovation-Group/SkyDrop#103]
Hi, like the minimalist layout, but would prefer having a clear indication of my transfer speed ans the uploaded percentage rather than the filling up...

**Comment by wellhat** [comment]
@ihubgit I assume you're referring to the iOS animation for displaying progress? 

We are planning an upgrade which will include a settings/advanced options screen, and could offer displaying upload speed / percentages as an optional toggle, so we can keep the default UI minimal. @tomShoutTheSecond fyi

**Comment by ihubgit** [comment]
great. Any ETA for this ?

**Comment by tomShoutTheSecond** [comment]
Hi @ihubgit thanks for the suggestion, unfortunately we have not found an accurate way to gauge these metrics due to Skynet's upload API behaviour.

The majority of the time taken for this request occurs after the file has been uploaded to the portal, as you can see when uploading in your browser at https://siasky.net . So what you are asking would mean jumping the progress bar quickly to 100% then showing an indeterminate progress bar for "processing" (we don't know how long it will take). Instead we prefer the current UX which estimates the expected upload time based on previous uploads, then attempts to move the progress bar smoothly towards 100% based on the expected time period.

We have spent a long time thinking about how we can improve this but this is the best solution we have for now.
